export default {
    UserName: {
        en: 'User Name',
        mm_uni: 'အမည်',
        mm_zg: 'အမည္',
        cn: '使用者名稱',
    },
    Password: {
        en: 'Password',
        mm_uni: 'စကားဝှက်',
        mm_zg: 'စကားဝွက္',
        cn: '密碼',
    },
    Register: {
        en: 'REGISTRATION',
        mm_uni: 'မှတ်ပုံတင်မည်',
        mm_zg: 'မွတ္ပံုတင္မည္',
        cn: '註冊',
    },
    Confirm: {
        en: 'CONFIRM',
        mm_uni: 'အတည်ပြုမည်',
        mm_zg: 'အတည္ျပဳမည္',
        cn: '確認',
    },
    Cancel: {
        en: 'CANCEL',
        mm_uni: 'ပယ်ဖျက်မည်',
        mm_zg: 'ပယ္ဖ်က္မည္',
        cn: '移除',
    },
    OK: {
        en: 'OK',
        mm_uni: 'လက်ခံပါမည်',
        mm_zg: 'လက္ခံပါမည္',
        cn: '好',
    },
    No_DATA: {
        en: 'There is no data.',
        mm_uni: 'အချက်အလက်မရှိသေးပါ...',
        mm_zg: 'အခ်က္အလက္မရွိေသးပါ...',
        cn: '沒有數據',
    },
    Pending: {
        en: 'Pending',
        mm_uni: 'စောင့်စားဆဲ',
        mm_zg: 'ေစာင္႕စားဆဲ',
        cn: '有待',
    },
    Old_Password: {
        en: 'Old Password',
        mm_uni: 'စကားဝှက်ဟောင်း',
        mm_zg: 'စကားဝွက္ေဟာင္း',
        cn: '舊密碼',
    },
    New_Password: {
        en: 'New Password',
        mm_uni: 'စကားဝှက်သစ်',
        mm_zg: 'စကားဝွက္သစ္',
        cn: '新密碼',
    },
    Retype_Password: {
        en: 'Retype Password',
        mm_uni: 'စကားဝှက်ပြန်ရိုက်ပါ',
        mm_zg: 'စကားဝွက္ျပန္ရိုက္ပါ',
        cn: '確認密碼',
    },
    Submit_Logout: {
        en: 'Submit & Logout',
        mm_uni: 'ထွက်မည်',
        mm_zg: 'ထြက္မည္',
        cn: '送出並登出',
    },
    My_Profile: {
        en: 'My profile',
        mm_uni: '',
        mm_zg: 'ကိုယ္ေရးမွတ္တမ္း',
        cn: '我的簡介',
    },
    New_display_name: {
        en: 'New Display Name',
        mm_uni: 'အမည်အသစ်',
        mm_zg: 'အမည္အသစ္',
        cn: '新的顯示名稱',
    },
    Submit: {
        en: 'Submit',
        mm_uni: 'အတည်ပြု',
        mm_zg: 'အတည္ျပဳ',
        cn: '送出',
    },
    Login: {
        en: 'Login',
        mm_uni: 'ဝင်ရောက်မည်',
        mm_zg: 'ဝင္ေရာက္မည္',
        cn: '登入',
    },
    Guest: {
        en: 'Guest',
        mm_uni: 'ဧည့်သည်',
        mm_zg: 'ဧည့္သည္',
        cn: '客人',
    },
    System_Settings: {
        en: 'System Settings',
        mm_uni: 'စနစ်အပြင်အဆင်',
        mm_zg: 'စနစ္အျပင္အဆင္',
        cn: '系統設置',
    },
    Change_my_password: {
        en: 'Change my password',
        mm_uni: 'စကားဝှက်အားပြောင်းလဲမည်',
        mm_zg: 'စကားဝွက္အားေၿပာင္းလဲမည္',
        cn: '變更密碼',
    },
    System_language: {
        en: 'System language',
        mm_uni: 'ဘာသာစကား',
        mm_zg: 'ဘာသာစကား',
        cn: '系統語言',
    },
    English: {
        en: 'English',
        mm_uni: 'အင်္ဂလိပ်စာ',
        mm_zg: 'အဂၤလိပ္စာ',
        cn: 'English',
    },
    Myanmar_Zawgyi: {
        en: 'Myanmar(Zawgyi)',
        mm_uni: 'မြန်မာစာ (ဇော်ဂျီ)',
        mm_zg: 'ၿမန္မာစာ (ေဇာ္ဂ်ီ)',
        cn: 'Myanmar(Zawgyi)',
    },
    Myanmar_Unicode: {
        en: 'Myanmar(Unicode)',
        mm_uni: 'မြန်မာစာ (ယူနီကုဒ်)',
        mm_zg: 'ၿမန္မာစာ (ယူနီကုဒ္)',
        cn: 'Myanmar(Unicode)',
    },
    Chinese: {
        en: 'Chinese',
        mm_uni: 'တရုတ်စာ',
        mm_zg: 'တ႐ုတ္စာ',
        cn: '緬文',
    },
    Logout: {
        en: 'Logout',
        mm_uni: 'ထွက်မည်',
        mm_zg: 'ထြက္မည္',
        cn: '登出',
    },
    Home: {
        en: 'Home',
        mm_uni: 'ပင်မစာမျက်နှာ',
        mm_zg: 'ပင္မစာမ်က္ႏွာ',
        cn: '首頁',
    },
    See_All: {
        en: 'See All',
        mm_uni: 'အားလုံးကြည့်မည်',
        mm_zg: 'အားလံုးၾကည့္မည္',
        cn: '查看全部',
    },

    Product: {
        en: 'Product',
        mm_uni: 'အစာအိတ်များ',
        mm_zg: 'အစာအိတ္မ်ား',
        cn: '產品',
    },
    Product_detail: {
        en: 'Product Detail',
        mm_uni: 'အစာအိတ်ဆိုင်ရာ အသေးစိတ်အချက်အလက်များ',
        mm_zg: 'အစာအိတ္ဆိုင္ရာ အေသးစိတ္အခ်က္အလက္မ်ား',
        cn: '產品內容',
    },
    Suitable_for: {
        en: 'Suitable For',
        mm_uni: 'အသုံးဝင်ပုံ',
        mm_zg: 'အသံုးဝင္ပံု',
        cn: '使用者簡介',
    },
    How_to_use: {
        en: 'How to Use',
        mm_uni: 'အသုံးပြုနည်း',
        mm_zg: 'အသံုးၿပဳနည္း',
        cn: '使用者簡介',
    },
    Add: {
        en: 'Add',
        mm_uni: 'ပေါင်းထည့်မည်',
        mm_zg: 'ေပါင္းထည့္မည္',
        cn: '加入',
    },
    Remove: {
        en: 'Remove',
        mm_uni: 'ဖယ်ရှားမည်',
        mm_zg: 'ဖယ္ရွားမည္',
        cn: '移除',
    },

    Cart: {
        en: 'Cart',
        mm_uni: 'ဝယ်ယူရန်စာရင်းသွင်းထားသည့်ပစ္စည်းများ',
        mm_zg: 'ဝယ္ယူရန္စာရင္းသြင္းထားသည့္ပစၥည္းမ်ား',
        cn: '購物車',
    },
    Checkout: {
        en: 'CheckOut',
        mm_uni: 'ငွေရှင်းမည်',
        mm_zg: 'ေငြရွင္းမည္',
        cn: '查看',
    },
    Choose_collection_point: {
        en: 'Choose a collecting point',
        mm_uni: 'အစာအိတ် လာရောက်ထုတ်ယူမည့်နေရာ',
        mm_zg: 'အစာအိတ္ လာေရာက္ထုတ္ယူမည့္ေနရာ',
        cn: '取車地點',
    },
    Collection_date: {
        en: 'Collecting Date',
        mm_uni: 'အစာအိတ် လာရောက်ထုတ်ယူမည့်နေ့',
        mm_zg: 'အစာအိတ္ လာေရာက္ထုတ္ယူမည့္ေန႕',
        cn: '取車日期',
    },
    Choose_payment_type: {
        en: 'Choose payment type',
        mm_uni: 'ငွေပေးချေမှုအမျိုးအစားများ',
        mm_zg: 'ေငြေပးေခ်မႈအမ်ိဳးအစားမ်ား',
        cn: '付款形式',
    },
    Remark: {
        en: 'Remark',
        mm_uni: 'မှတ်ချက်',
        mm_zg: 'မွတ္ခ်က္',
        cn: '備註留言',
    },
    Payment_type: {
        en: 'Payment Type',
        mm_uni: 'ငွေပေးချေမှုအမျိုးအစား',
        mm_zg: 'ေငြေပးေခ်မႈအမ်ိဳးအစား',
        cn: '付款方式',
    },
    NORMAL_PAY: {
        en: 'Normal Pay',
        mm_uni: 'ပုံမှန်ငွေပေးချေမှုပုံစံ',
        mm_zg: 'ပံုမွန္ေငြေပးေခ်မႈပံုစံ',
        cn: '一般支付',
    },
    PROGRAM_PAY: {
        en: 'Program Pay',
        mm_uni: 'ဘဏ်နှင့်မွေးမြူရေးလုပ်ငန်းချေးငွေ',
        mm_zg: 'ဘဏ္ႏွင့္ေမြးၿမဴေရးလုပ္ငန္းေခ်းေငြ',
        cn: '貸款支付',
    },
    Order: {
        en: 'Order',
        mm_uni: 'မှာယူမည်',
        mm_zg: 'မွာယူမည္',
        cn: '下單',
    },
    Order_list: {
        en: 'Order List',
        mm_uni: 'မှာယူထားသည့်ပစ္စည်းစာရင်း',
        mm_zg: 'မွာယူထားသည့္ပစၥည္းစာရင္း',
        cn: '下單目錄',
    },
    Total_weight: {
        en: 'Total Weight',
        mm_uni: 'စုစုပေါင်းအလေးချိန်',
        mm_zg: 'စုစုေပါင္းအေလးခ်ိန္',
        cn: '總重',
    },
    Total_amount: {
        en: 'Total Amount',
        mm_uni: 'စုစုပေါင်းငွေပမာဏ',
        mm_zg: 'စုစုေပါင္းေငြပမာဏ',
        cn: '總數量',
    },
    Discount: {
        en: 'Discount',
        mm_uni: 'လျှော့ဈေး',
        mm_zg: 'ေလွ်ာ့ေစ်း',
        cn: '折扣',
    },
    Net_amount: {
        en: 'Net Amount',
        mm_uni: 'အသားတင်ငွေပမာဏ',
        mm_zg: 'အသားတင္ေငြပမာဏ',
        cn: '淨價格',
    },
    Transportation_Charges: {
        en: 'Transportation',
        mm_uni: 'ပို့ဆောင်ခ',
        mm_zg: 'ပို႔ေဆာင္ခ',
        cn: '运输费',
    },
    Collect_at: {
        en: 'Collect will',
        mm_uni: 'လာရောက်ထုတ်ယူမည်',
        mm_zg: 'လာေရာက္ထုတ္ယူမည္',
        cn: '取貨於',
    },
    Ordered_at: {
        en: 'Ordered at',
        mm_uni: 'မှာယူသည်',
        mm_zg: 'မွာယူသည္',
        cn: '下單於',
    },
    Issue_List: {
        en: 'Issue List',
        mm_uni: 'ထုတ်ယူထားသော ပစ္စည်းစာရင်း',
        mm_zg: 'ထုတ္ယူထားေသာ ပစၥည္းစာရင္း',
        cn: '问题清单',
    },
    Re_Order: {
        en: 'Re Order',
        mm_uni: 'ပြန်လည်မှာယူရန်',
        mm_zg: 'ျပန္လည္မွာယူရန္',
        cn: '重新订阅',
    },
    Location: {
        en: 'Location',
        mm_uni: 'နေရာ',
        mm_zg: 'ေနရာ',
        cn: '地点',
    },
    Status: {
        en: 'Status',
        mm_uni: 'အခြေအနေ',
        mm_zg: 'အေျခအေန',
        cn: '状态',
    },
};
